package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/b-sea/supply-run-api/internal/auth"
	"github.com/b-sea/supply-run-api/internal/cookbook/app/query"
	"github.com/b-sea/supply-run-api/internal/cookbook/graphql/model"
	"github.com/google/uuid"
	"github.com/sirupsen/logrus"
)

// FindRecipeSnippets is the resolver for the findRecipeSnippets field.
func (r *queryResolver) FindRecipeSnippets(ctx context.Context, filter *model.RecipeFilter) ([]*model.RecipeSnippet, error) {
	logrus.Info(auth.FromContext(ctx))

	var queryFilter *query.RecipeFilter
	if filter != nil {
		queryFilter = &query.RecipeFilter{
			Name: filter.Name,
			// TagIDs: filter.TagIDs,
		}
	}

	r.App.Queries.FindRecipeSnippets.Handle(uuid.New(), queryFilter)
	return nil, nil
}

// Recipe is the resolver for the recipe field.
func (r *queryResolver) Recipe(ctx context.Context, id string) (*model.Recipe, error) {
	panic(fmt.Errorf("not implemented: Recipe - recipe"))
}

// AllUnits is the resolver for the allUnits field.
func (r *queryResolver) AllUnits(ctx context.Context) ([]*model.Unit, error) {
	panic(fmt.Errorf("not implemented: AllUnits - allUnits"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
