// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type Ingredient struct {
	ID       string  `json:"id"`
	Unit     *Unit   `json:"unit"`
	Quantity float64 `json:"Quantity"`
}

type Query struct {
}

type Recipe struct {
	ID          string        `json:"id"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   *time.Time    `json:"updatedAt,omitempty"`
	Owner       string        `json:"owner"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	URL         *string       `json:"url,omitempty"`
	Ingredients []*Ingredient `json:"ingredients,omitempty"`
	Steps       []string      `json:"steps,omitempty"`
	Serving     int           `json:"serving"`
}

type RecipeFilter struct {
	Name   *string  `json:"name,omitempty"`
	TagIDs []string `json:"tagIDs,omitempty"`
}

type RecipeSnippet struct {
	ID          string    `json:"id"`
	CreatedAt   time.Time `json:"createdAt"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

type Unit struct {
	ID        string            `json:"id"`
	CreatedAt time.Time         `json:"createdAt"`
	UpdatedAt *time.Time        `json:"updatedAt,omitempty"`
	Owner     string            `json:"owner"`
	Name      string            `json:"name"`
	Symbol    string            `json:"symbol"`
	Type      UnitType          `json:"type"`
	System    MeasurementSystem `json:"system"`
}

type MeasurementSystem string

const (
	MeasurementSystemNone     MeasurementSystem = "NONE"
	MeasurementSystemImperial MeasurementSystem = "IMPERIAL"
	MeasurementSystemMetric   MeasurementSystem = "METRIC"
)

var AllMeasurementSystem = []MeasurementSystem{
	MeasurementSystemNone,
	MeasurementSystemImperial,
	MeasurementSystemMetric,
}

func (e MeasurementSystem) IsValid() bool {
	switch e {
	case MeasurementSystemNone, MeasurementSystemImperial, MeasurementSystemMetric:
		return true
	}
	return false
}

func (e MeasurementSystem) String() string {
	return string(e)
}

func (e *MeasurementSystem) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MeasurementSystem(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MeasurementSystem", str)
	}
	return nil
}

func (e MeasurementSystem) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UnitType string

const (
	UnitTypeNone   UnitType = "NONE"
	UnitTypeMass   UnitType = "MASS"
	UnitTypeVolume UnitType = "VOLUME"
)

var AllUnitType = []UnitType{
	UnitTypeNone,
	UnitTypeMass,
	UnitTypeVolume,
}

func (e UnitType) IsValid() bool {
	switch e {
	case UnitTypeNone, UnitTypeMass, UnitTypeVolume:
		return true
	}
	return false
}

func (e UnitType) String() string {
	return string(e)
}

func (e *UnitType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UnitType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UnitType", str)
	}
	return nil
}

func (e UnitType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
