package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"errors"

	"github.com/b-sea/supply-run-api/internal/entity"
	"github.com/b-sea/supply-run-api/internal/graphql/model"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id model.ID) (model.Node, error) {
	switch id.Kind {
	case model.RecipeKind:
		found, err := r.queries.GetRecipe(ctx, id.Key)
		if err != nil {
			if errors.Is(err, entity.ErrNotFound) {
				return model.NotFoundError{ID: id}, nil
			}

			return nil, err
		}

		return model.NewRecipe(found), nil

	case model.UnitKind:
		found, err := r.queries.GetUnits(ctx, []entity.ID{id.Key})
		if err != nil {
			return nil, err
		}

		if len(found) == 0 {
			return model.NotFoundError{ID: id}, nil
		}

		return model.NewUnit(found[0]), nil

	case model.UserKind:
		found, err := r.queries.GetUsers(ctx, []entity.ID{id.Key})
		if err != nil {
			return nil, err
		}

		if len(found) == 0 {
			return model.NotFoundError{ID: id}, nil
		}

		return model.NewUser(found[0]), nil

	default:
		return model.NotFoundError{ID: id}, nil
	}
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
