package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"errors"

	"github.com/b-sea/supply-run-api/internal/entity"
	"github.com/b-sea/supply-run-api/internal/graphql/dataloader"
	"github.com/b-sea/supply-run-api/internal/graphql/model"
)

// Unit is the resolver for the unit field.
func (r *ingredientResolver) Unit(ctx context.Context, obj *model.Ingredient) (model.UnitResult, error) {
	result, err := dataloader.GetUnit(ctx, obj.UnitID)
	if err != nil {
		return nil, err
	}

	return result, nil
}

// FindRecipes is the resolver for the findRecipes field.
func (r *queryResolver) FindRecipes(ctx context.Context, filter *model.RecipeFilter, page *model.Page, order *model.Order) (*model.RecipeConnection, error) {
	result, err := r.queries.FindRecipes(
		ctx,
		model.NewQueryRecipeFilter(filter),
		model.NewQueryPagination(page),
		model.NewQueryOrder(order),
	)
	if err != nil {
		return nil, err
	}

	return model.NewRecipeConnection(result), nil
}

// Recipe is the resolver for the recipe field.
func (r *queryResolver) Recipe(ctx context.Context, id model.ID) (model.RecipeResult, error) {
	if id.Kind != model.RecipeKind {
		return model.NotFoundError{ID: id}, nil
	}

	result, err := r.queries.GetRecipe(ctx, id.Key)
	if err != nil {
		if errors.Is(err, entity.ErrNotFound) {
			return model.NotFoundError{ID: id}, nil
		}

		return nil, err
	}

	return model.NewRecipe(result), nil
}

// FindTags is the resolver for the findTags field.
func (r *queryResolver) FindTags(ctx context.Context, filter *string) ([]string, error) {
	result, err := r.queries.FindTags(ctx, filter)
	if err != nil {
		return nil, err
	}

	return result, nil
}

// CreatedBy is the resolver for the createdBy field.
func (r *recipeResolver) CreatedBy(ctx context.Context, obj *model.Recipe) (model.UserResult, error) {
	result, err := dataloader.GetUser(ctx, obj.CreatedByID)
	if err != nil {
		return nil, err
	}

	return result, nil
}

// UpdatedBy is the resolver for the updatedBy field.
func (r *recipeResolver) UpdatedBy(ctx context.Context, obj *model.Recipe) (model.UserResult, error) {
	result, err := dataloader.GetUser(ctx, obj.UpdatedByID)
	if err != nil {
		return nil, err
	}

	return result, nil
}

// Ingredient returns IngredientResolver implementation.
func (r *Resolver) Ingredient() IngredientResolver { return &ingredientResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Recipe returns RecipeResolver implementation.
func (r *Resolver) Recipe() RecipeResolver { return &recipeResolver{r} }

type ingredientResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type recipeResolver struct{ *Resolver }
