couchbase:
  url: 
  user:
  pwd:

tokens:
  signMethod: "RS256"
  publicKeyPath: 
  privateKeyPath: 
  issuer: "supply-run.auth.service"
  audience: ""
  accessTimeout: 900
  refreshTimeout: 2592000

passwords:
  minLength: 12
  maxLength: 150
  upper: true
  lower: true
  number: true
  special: true
  pepper:
