package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/b-sea/supply-run-api/internal/auth"
	"github.com/b-sea/supply-run-api/internal/server/graphql/model"
)

// Tokens is the resolver for the tokens field.
func (r *mutationResolver) Tokens(ctx context.Context, input model.TokenInput) (*model.Tokens, error) {
	tokens, err := r.Auth.Tokens(
		ctx,
		auth.TokensCommand{
			Username: input.Username,
			Password: input.Password,
		},
	)
	if err != nil {
		return nil, err
	}

	return &model.Tokens{
		Access:  tokens.Access,
		Refresh: tokens.Refresh,
	}, nil
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input model.CreateAccountInput) (bool, error) {
	if err := r.Auth.CreateAccount(
		ctx,
		auth.CreateAccountCommand{Username: input.Username, Password: input.Password},
	); err != nil {
		return false, err
	}

	return true, nil
}

// UpdateAccount is the resolver for the updateAccount field.
func (r *mutationResolver) UpdateAccount(ctx context.Context, input model.UpdateAccountInput) (bool, error) {
	if err := r.Auth.UpdateAccount(
		ctx,
		auth.UpdateAccountCommand{Password: input.Password},
	); err != nil {
		return false, err
	}

	return true, nil
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context) (bool, error) {
	if err := r.Auth.DeleteAccount(ctx); err != nil {
		return false, err
	}

	return true, nil
}

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context) (*model.Account, error) {
	account, err := r.Auth.GetAccount(ctx)
	if err != nil {
		return nil, err
	}

	return &model.Account{
		ID:        account.ID().String(),
		Username:  account.Username(),
		CreatedAt: account.CreatedAt(),
		UpdatedAt: account.UpdatedAt(),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
