package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"
)

// Temp is the resolver for the temp field.
func (r *mutationResolver) Temp(_ context.Context) (string, error) {
	return "temp mutation", nil
}

// Temp is the resolver for the temp field.
func (r *queryResolver) Temp(_ context.Context) (string, error) {
	return "temp query", nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
