version: "2"

linters:
  default: all

  exclusions:
    rules:
      # Exclude some linters from running on gqlgen generated files.
      - path: internal/server/graphql/
        linters:
          - ireturn

  disable:
   - wsl
   - depguard
   - noinlineerr
   - exhaustruct

settings:
  wsl_v5:
    allow-first-in-block: true
    allow-whole-block: false
    branch-max-lines: 2

issues:
  max-issues-per-linter: 0
  max-same-issues: 0


run:
  tests: false
