version: "2"

linters:
  default: all

  exclusions:
    paths:
      # Skip mocks completely
      - internal/mock

    rules:
      - path: cmd/main.go
        linters:
          - mnd

      # Domain options should allow dynamic errors.
      - path: internal/recipe/option.go
        linters:
          - err113

      # Exclude some linters from running on gqlgen generated files.
      - path: internal/graphql/resolver
        linters:
          - ireturn
          - wrapcheck

  disable:
   - wsl
   - depguard
   - noinlineerr
   - exhaustruct

  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    
    varnamelen:
      ignore-names:
        - id
        - r
        - i

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  tests: false
