issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

linters:
  enable-all: true
  disable:
    - exhaustruct
    - depguard
    - testifylint
    - godox
    - nlreturn
    - musttag
    - dupl
    - execinquery
    - gomnd
    - exportloopref
    - revive
    - stylecheck
    - wrapcheck

linters-settings:
  cyclop:
    max-complexity: 18
    package-average: 10.0

  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: camel
        yaml: camel
        mapstructure: camel

  varnamelen:
    ignore-type-assert-ok: true
    ignore-map-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - id
      - ok

run: 
  tests: false