profile: tools/cover.out

threshold:
  file: 70
  package: 80
  total: 95

exclude:
  paths:
    - cmd/main.go
    # exlude telemetry
    - internal/metrics
    - pkg/logger
    # exclude gqlgen generated file
    - internal/server/graphql/resolver/generated\.go$
    # exclude gqlgen generated models
    - internal/server/graphql/model

force-annotation-comment: false
