profile: tools/cover.out

threshold:
  file: 70
  package: 80
  total: 90

exclude:
  paths:
    - cmd/supplyrun
    - internal/metrics
    - internal/mock
    - internal/graphql/handler\.go
    - internal/graphql/telemetry\.go
    - internal/graphql/model/models_gen\.go
    - internal/graphql/resolver/generated\.go

force-annotation-comment: true
